### ISSUE TITLE
Version published to rubygems doesn't match this repo

### ISSUE THREAD

**Issue by jleppert** [lautis/uglifier#90]
Umm....I upgraded to 2.7.2, which is the current version in this repository. However, it doesn't have the new options for source maps.

It's really confusing when you have different documentation for options and the same version identifier (2.7.2) and THAT is different than what is published to rubygems under the same version number?

I would make a pull request but this seems to be some kind of issue with the administration of this project and proper respect of versioning.

**Comment by lautis** [comment]
What's in the repo will become 3.0.0 when released. I've usually bumped the version string in code only when doing the release. You can find documentation for 2.7.2 at http://www.rubydoc.info/gems/uglifier.

In this case having not-yet-released version in the master branch especially since pretty much all links to the project only point to the git repository and not e.g. generated documentation. I'll try to keep this in mind with future changes.
